name: Deploy to polygron testnetwork

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs: 
  build-image:
    name: Build container
    runs-on: ubuntu-18.04
    environment: production

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Setup yarn
      run: npm install -g yarn
      
    - run: |
        yarn
        yarn graph auth --product=hosted-service ${{ secrets.THE_GRAPH_KEY }}
        yarn prepare:mumbai
        yarn codegen
        yarn build
        yarn deploy